### ISSUE TITLE
Consider SCSS formatting via "stylefmt" as part of build

### ISSUE THREAD

**Issue by benbridge** [flickerbox/fabric#1]
I like the idea of using stylefmt because: 

> stylefmt is a tool that automatically formats CSS according to stylelint rules

Benefits: 
- Once we settle on the linting rules, we can apply formatting based on them automatically resulting in consistent stylesheets without manual formatting
- "stylefmt/stylelint" is part of the node ecosystem so it fit's better with our use of node-sass
- less dependencies, "scss-lint" requires Ruby and Ruby gems

Drawbacks: 
- "scss-lint" would need to be replaced with "stylelint" for this to work.

[stylefmt project page](https://github.com/morishitter/stylefmt)
[scss-lint project page](https://github.com/brigade/scss-lint)

**Comment by codyrobert** [comment]
I like this. We'll have to notify our team to do a fresh `npm install` on projects after this gets integrated, but that's no problem - just mentioning as a to-do.

Can you put together a pr?

**Comment by tmaier** [comment]
You should consider to use http://stylelint.io instead of scss-lint. Both use the same config file format.

**Comment by chrislarrycarl** [comment]
Since we've adjust fabric to be build agnostic I think we can close this issue?
